apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveries-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveries
  template:
    metadata:
      labels:
        app: deliveries
    spec:
      containers:
        - image: feniksa18/deliveries:2022-12-04-16-29-49
          name: deliveries
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ella.db.elephantsql.com:5434/fajqyywa
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: fajqyywa
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass2
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8181
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: deliveries
spec:
  type: LoadBalancer
  ports:
    - port: 8181
      protocol: TCP
      targetPort: server
  selector:
    app: deliveries
