apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveries-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveries
  template:
    metadata:
      labels:
        app: deliveries
    spec:
      containers:
        - image: feniksa18/deliveries:2022-12-03-13-20-36
          name: deliveries
          env:
            - name: KUMULUZEE_DATASOURCES1_CONNECTIONURL
              value: jdbc:postgresql://ella.db.elephantsql.com:5432/fajqyywa
            - name: KUMULUZEE_DATASOURCES1_USERNAME
              value: fajqyywa
            - name: KUMULUZEE_DATASOURCES1_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: KUMULUZEE_DATASOURCES1_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: deliveries
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: deliveries
